### PR TITLE
Update: migrated to Go Modules.

### PR DESCRIPTION
**Pull request by scharissis**
*Description of changes:*
Migrated to [Go modules](https://golang.org/doc/go1.11#modules).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by scharissis** [comment]
@PettitWesley - Hi. Is this project still maintained and accepting PR's?

**Comment by scharissis** [comment]
@jamesiri , @fenxiong , @PettitWesley - is this project still maintained and accepting PR's?

**Comment by PettitWesley** [comment]
@scharissis Yes it is... just no active work since it does what we need already... let me take a look at this..

**Review by PettitWesley — APPROVED** [review]

**Comment by PettitWesley** [comment]
@scharissis Thank you. By the way- how do you use this project?

**Comment by scharissis** [comment]
Great to hear! Thanks for the library and also the merge. Hopefully Brazil/Apollo don't complain too much after the merge ;)

I might have a few more features coming your way if you're amenable.

My main use case right now is to automate the generation of fluent config for a custom filter plugin. Hundreds of *.conf files, which are @included in the main conf file. The input is an internal DSL specifying the desired filter rules.
(This filter is in the process of being OSS'ed, but is not currently)

Thing is, since it's a custom plugin, the base Fluent(d|bit) templates can't possibly know the format of the plugin. So I was thinking that could be a nice next contribution; to facilitate the ability for one to add to the default template, or just supply one themselves (the latter probably being far easier).

**Comment by PettitWesley** [comment]
@scharissis so a way to add a generic filter definition? That sounds interesting

**Comment by scharissis** [comment]
@PettitWesley Yes, exactly. I think it would add a lot of utility to the library. I'll have a think about it next week and if I come up with a good way to do it I'll open an issue and run the idea past you. (Or, if it ends up being simple enough, just submit a PR instead)

**Pull request merged**
